# Note that the following stanza uses CircleCI 2.1 to make use of a Reusable Executor
# This allows defining a docker image to reuse across jobs.
# visit https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors to learn more.

version: 2.1

# ****** High-level description: *********
# 
# 1) We can have differents executors. at moment we need only golang one. Each worker can be a diff docker container or other resource type. (see upstream doc)
#
# 2) The first part jobs is just what this jobs/task execute.
#
# 3) At the end you have the workflow which allow us to define parallelism and dependencies between jobs/tasks

executors:
  golang-executor:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/kubic-project/registries-operator
  kind-executor:
    docker:
      - image: golang:1.11


jobs:
  build-and-run-unit-tests:
    executor: golang-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-pkg-cache

      - run:
          name: Build project from src
          command: make
 
      - save_cache:
          key: v3-pkg-cache
          paths:
            - /go/pkg

      - run:
          name: Execute unit-tests
          command: make test

  build-docker-image:
    executor: golang-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build the Docker image
          command: make clean _vendor-download docker-image

  tests-lint:
    executor: golang-executor
    steps:
      - checkout
      - run:
          name: Execute lint tests
          command: make check

  # setup cluster with kind and run e2e tests       
  e2e-operator-tests:
    machine: true
    working_directory: /go/src/github.com/kubic-project/registries-operator
    steps:
      - checkout

      - run:
          name: Install Golang
          command: |
            set -x
            sudo add-apt-repository ppa:gophers/archive
            sudo apt-get update
            sudo apt-get install golang-1.10-go

      - run:
          name: Install Docker Client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Setup Kubernetes Cluster with kind
          command: |
            go get github.com/kubernetes-sigs/kind
            kind create cluster --name="1"
            echo "--- docker containers --- "
            docker ps
            echo "--- ***************** ---"
            export KUBECONFIG="$(kind get kubeconfig-path --name="1")"
       
      - run:
          name: Run e2e-tests for k8s operator
          command: make e2e-tests

workflows:
  version: 2.1

  kubic:
    jobs:
      - build-and-run-unit-tests
      - build-docker-image
      - tests-lint
      - e2e-operator-tests
